### ISSUE TITLE
Benchmark to RENATE

### ISSUE THREAD

**Issue by SzondyB** [gergopokol/renate-od#50] opened 2019-04-16 16:11 UTC

**Comment by asztalosors** [comment] 2019-06-14 13:33
Added visualization tools for benchmark. Needs some cosmetics done as well.
Benchmark Fails!
Three test-cases are highlighted:
1. Li beam in D plasma @ 60 keV (9 levels)
2. Na beam in H plasma @ 60 keV (8 levels)
3. H beam in He plasma @ 60 keV (6 levels)

There seems to be some systematic discrepancies between RENATE and ROD: 
1. ROD rates result in stronger beam attenuation and greater relative population of excited states.
2. RENATE profiles seem to be a bit smoother than those of ROD.

Solutions and investigations:
1. Double check RENATE and ROD input data. 
2. Have a closer look at previous benchmark attempt to different numerical solver.
3. (MOST likely) Recheck CRM and see whether the matrix is correctly constructed (There have been recorded issues  with the new CRM we are using).

![Dplasma_Libeam@60keV](https://user-images.githubusercontent.com/26080385/59512314-c282f600-8eb8-11e9-833a-f13f5b82681a.png)
![Hplasma_Nabeam@60keV](https://user-images.githubusercontent.com/26080385/59512315-c282f600-8eb8-11e9-8597-d0e8161ae94f.png)
![Heplasma_Hbeam@60keV](https://user-images.githubusercontent.com/26080385/59512316-c282f600-8eb8-11e9-876f-af3c4a272c4c.png)

**Comment by asztalosors** [comment] 2019-08-27 07:53
There seems to be an error in the calculation of the beam velocity. Beam energy is given in keV but for beam velocity calculation the value is not transformed in eV. Resulting in beam velocity of ~ 30 times lower then reality. This results in an overestimation of the spontaneous emission terms in the CRM. This might result in the discrepancy witnessed so far.

**Comment by asztalosors** [comment] 2019-08-27 08:16
Adding plots for regression testing of:
1. He plasma with H beam @ 60keV
![He_plasma_H_beam](https://user-images.githubusercontent.com/26080385/63753641-bdc4c000-c8b3-11e9-81fb-f021cb082878.png)
2. D plasma with Li beam @ 60keV
![D_plasma_Li_beam](https://user-images.githubusercontent.com/26080385/63753606-aab1f000-c8b3-11e9-86c9-b9adae82f243.png)
3. H plasma with Na beam @ 60keV
![H_plasma_Na_beam](https://user-images.githubusercontent.com/26080385/63753634-b7cedf00-c8b3-11e9-8666-dc7d5748e6b7.png)

**Comment by asztalosors** [comment] 2019-08-27 08:18
There are some minor discrepancies between the two plots. Under investigation. The major problem seems to be fixed in the CRM applied in RENATE-OD

**Comment by SzondyB** [comment] 2019-08-27 12:47
Juhéj!!!!!

Asztalos Örs <notifications@github.com> ezt írta (időpont: 2019. aug. 27.,
K, 10:18):

**Comment by asztalosors** [comment] 2019-09-03 23:00
Plot of relative error for Li in D plasma.
![Relative error D_plasma Li beam](https://user-images.githubusercontent.com/26080385/64214085-57413280-ceaf-11e9-82d8-e7216b4c4039.png)

**Comment by asztalosors** [comment] 2019-09-03 23:06
Further plots of relative error: for
Na:
![Na_relative error](https://user-images.githubusercontent.com/26080385/64214286-2e6d6d00-ceb0-11e9-9f14-6ad07b187523.png)
and for H:
![Relative_error_H in He](https://user-images.githubusercontent.com/26080385/64214285-2a414f80-ceb0-11e9-9e96-45a2a015f9fe.png)

**Comment by asztalosors** [comment] 2019-09-03 23:08
It is clear that the relative error on higher atomic levels is larger up to 30 % for H projectiles, 15% for Li projectiles. Ground state relative error is small in range of 1 - 5%.

Relative error for Na is irrelevant.

**Comment by asztalosors** [comment] 2019-09-03 23:49
The regression tests should include more pure plasma oriented benchmarks and be done not in the framework of a Unittest.

**Closed by asztalosors** 2019-09-03 23:49 UTC
Labels: support

**Comment by gergopokol** [comment] 2019-09-04 11:13
For the time being, we can accept the regression tests (actually RENATE benchmarks) with the given precisions. Expected precisions are to be updated in the next release.

Later true regression tests are to be set up using old runs of RENATE-OD as reference.
