### ISSUE TITLE
Implement changing parameter ode solver

### ISSUE THREAD

**Issue by SzondyB** [gergopokol/renate-od#5] opened 2017-03-16 08:34 UTC
Extension of constant parameter ode solver.

**Comment by gergopokol** [comment] 2018-03-09 16:27
**Major restructuring** in the `feature_solver-refactoring` branch.

**Comment by gergopokol** [comment] 2018-03-10 21:30
**CRM solver works** with automatic data download and XML input files. Should be further tested, and further refactoring is to be done with continuous regression testing. Can be run from Console:

```
from crm_solver.beamlet import Beamlet
b = Beamlet()
b.plot_populations()
```

**Comment by gergopokol** [comment] 2018-03-12 21:03
This is to be implemented! :)

![img_20180307_165239](https://user-images.githubusercontent.com/24719037/37309392-1ba48532-2641-11e8-80f9-7b42ea6a6180.jpg)

**Comment by gergopokol** [comment] 2018-03-20 01:29
This is technically working, so merged to master.
The result is, however, clearly wrong, with unchanged level0. The problem is most probably in `CoefficientMatrix.assemble_terms()` with mixing up the dimensions of the rate matrixes.
This is also probably not ok: `from_level + 1:self.number_of_levels`. 
This needs to be checked and benchmarked to RENATE!

**Comment by gergopokol** [comment] 2018-03-21 18:48
test_profiles.h5 density was in wrong dimensions. Had to be multiplied by 10^19. The structure also changed by introducing the `'profiles'` key to test_profiles.h5. **Needs to be re-downloaded!**

Output looks nice. Should benchmark to old RENATE!

**Comment by SzondyB** [comment] 2018-04-05 11:11
Successful Benchmark:
![benchmark](https://user-images.githubusercontent.com/25754664/38362909-d186a9c2-38d2-11e8-8fd6-04a26407c6ed.png)

**Comment by gergopokol** [comment] 2019-06-20 17:54
This is being continued in #56 and #50 .

**Closed by gergopokol** 2019-06-20 17:54 UTC
Labels: enhancement
